version: "3.4"

networks:
  default:
    external: false
  db_net:
    external: true

# we use network_mode: host for services, because I am lazy and can't get containers to communicate
services:
  nginx:
    network_mode: host
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - northstar
  kraken:
    network_mode: host
    restart: unless-stopped
    build:
      context: kraken
    ports:
      - 8001:8000  # unused, host network
    depends_on:
      - redis
    volumes:
      - "./kraken:/app"
      - "./common:/common"
  northstar:
    network_mode: host
    restart: unless-stopped
    environment:
      - RUN_LEVEL=dev
    build:
      dockerfile: deploy/Dockerfile.server
      context: northstar
      target: dev
    ports:
      - 8000:8000  # unused, host network
    volumes:
      - "./northstar:/code"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: northstar
    networks:
      - db_net
    volumes:
      - "../.docker_data/postgres:/var/lib/postgresql/data"
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "../.docker_data/redis:/data"
