version: "3.4"

networks:
  default:
    external: false
  db_net:
    external: true

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - northstar
    networks:
      - default
  northstar:
    restart: unless-stopped
    environment:
      - RUN_LEVEL=dev
    build:
      dockerfile: docker/Dockerfile.server
      context: northstar
      target: dev
    volumes:
      - "./northstar:/code"
    depends_on:
      - postgres
      - redis
    networks:
      - default
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: northstar
    networks:
      - db_net
      - default
    volumes:
      - "../.docker_data/postgres:/var/lib/postgresql/data"
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "../.docker_data/redis:/data"
    networks:
      - default
