version: "3.4"

networks:
  db_net:
    external: true

services:
  server:
    network_mode: host
    restart: unless-stopped
    environment:
      - RUN_LEVEL=dev
    build:
      dockerfile: northstar/docker/Dockerfile.server
      context: northstar
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - "./northstar:/code"
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: northstar
    networks:
      - db_net
    volumes:
      - "../.docker_data/postgres:/var/lib/postgresql/data"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "../.docker_data/redis:/data"
